version: '3.8'
services:
  your-service:
    image: modular-slackbots
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 5000M